### ISSUE TITLE
알고리즘 스터디 1일차 문제

### ISSUE THREAD

**Issue by Yebin46** [round26/Algorithm#1]
[백준 2606번 바이러스](https://www.acmicpc.net/problem/2606)

그래프 탐색 문제입니다.
백준에는 문제가 많아서 [이 블로그](https://covenant.tistory.com/132)의 추천 문제를 가져와봤어요!

감사합니다😀

**Comment by gistarrr** [comment]
확인했어요~

**Comment by pkpete** [comment]
확인했습니다~

**Comment by danny980521** [comment]
확인했습니다!
